only_rules:
  - empty_count
  - missing_docs
  - unused_import
  - capture_variable
  - unused_declaration

analyzer_rules:
  - unused_import
  - capture_variable
  - unused_declaration

included:

excluded:

force_cast: warning
force_try:
  severity: warning
line_length: 110
type_body_length:
  - 150
  - 300
file_length:
  warning: 200
  error: 400
type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
  allowed_symbols: "_"
identifier_name:
  min_length:
    warning: 3
    error: 2
  excluded:
    - x
    - y
    - id
    - uid
    - URL
  allowed_symbols: "_"

custom_rules:
  prohibit_lower_snake_case:
    name: "Prohibit Lower Snake Case"
    regex: "[a-z]+_[a-z]+"
    message: "Identifiers should not be written in lower snake case."
    severity: error

reporter: "xcode"
